### ISSUE TITLE
Причем в статье слово "кросс-платформенное"?

### ISSUE THREAD

**Issue by mediaexplorer74** [dreamer-dead/chromium-sample-app#2]
Привет. Внимательно прочитал статью, просмотрел код примера. И возник "one dev question": кросс-платформу к чему приплели в заголовке своего творения? Чисто хайпануть?
Вот если б XamarinForms или UNO или Avalonia (они не вчера появились) задействованы были, я б еще понял. А так это всё ни о чем :(

**Comment by dreamer-dead** [comment]
Когда сможете объяснить, что помешает коду в статье компилироваться и работать под несколькими операционными системами, возвращайтесь.
